name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # تأكد من استخدام إصدار Flutter المناسب

      - name: Verify project structure
        run: ls -la

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./

      - name: Build iOS app
        run: flutter build ios --release
        working-directory: ./

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ./build/ios/iphoneos
