name: KPI App iOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        channel: stable
        cache: true
        cache-key: flutter-pub-cache

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          **/build/
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

    - name: Install dependencies
      run: |
        flutter pub get
        flutter precache --ios
      working-directory: .

    - name: Analyze code
      run: flutter analyze .
      working-directory: .

    - name: Run tests
      run: flutter test
      working-directory: .

    - name: Build iOS (Release)
      run: |
        flutter build ios --release --no-codesign \
        --dart-define=APP_ENV=prod \
        --dart-define=APP_VERSION=$(git describe --tags)
      working-directory: .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: kpi-app-ios
        path: build/ios/iphoneos/Runner.app
        retention-days: 5
